### ISSUE TITLE
SCP-079 crashes the server upon spawning

### ISSUE THREAD

**Issue by not-pyroman** [Exiled-Team/EXILED#1835] opened 2023-05-27 07:39 UTC
**Describe the bug**
Whenever the server tries to spawn a player as SCP-079, it experiences a segmentation fault and crashes.
**To Reproduce**
1. have anyone spawn as 079 or be changed to SCP-079
2. Server crashes and players time out

**Expected behavior**
The server does not crash and continues on as normal.

**Server logs**
[https://pastebin.com/S5UeuWKq](url)

**EXILED Version ("latest" is not a version):**
7.0.0-rc.4 (Testing release, commit 25a8a2d + PR#1832)

**Results of `show plugins` command in console:**
```
[2023-05-27 08:40:41.557 +02:00] Total number of plugins: 14
                                 Enabled plugins: 9
                                 Disabled plugins: 5
                                 
                                 Exiled.Events:
                                        - Author: Exiled Team
                                        - Version: 7.0.0.0
                                        - Required Exiled Version: 7.0.0.0
                                        - Prefix: exiled_events
                                        - Priority: Highest
                                 SCPUtils:
                                        - Disabled
                                        - Author: Terminator_97#0507
                                        - Version: 5.2.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: s_c_p_utils
                                        - Priority: Medium
                                 Admin Tools:
                                        - Author: Originally by Joker119. Modifications by KoukoCocoa & Thomasjosif
                                        - Version: 6.0.0.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: AT
                                        - Priority: Medium
                                 MapEditorReborn:
                                        - Disabled
                                        - Author: Michal78900
                                        - Version: 2.2.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: map_editor_reborn
                                        - Priority: Medium
                                 Exiled.CustomItems:
                                        - Disabled
                                        - Author: Exiled Team
                                        - Version: 7.0.0.0
                                        - Required Exiled Version: 7.0.0.0
                                        - Prefix: exiled_custom_items
                                        - Priority: Medium
                                 Common Utilities:
                                        - Author: Joker119
                                        - Version: 7.0.3.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: CommonUtilities
                                        - Priority: Medium
                                 Exiled.CustomRoles:
                                        - Author: Exiled Team
                                        - Version: 7.0.0.0
                                        - Required Exiled Version: 7.0.0.0
                                        - Prefix: exiled_custom_roles
                                        - Priority: Medium
                                 Exiled.CreditTags:
                                        - Author: Babyboucher20 & iRebbok & Exiled Team
                                        - Version: 7.0.0.0
                                        - Required Exiled Version: 7.0.0.0
                                        - Prefix: exiled_credits
                                        - Priority: Medium
                                 Exiled.Updater:
                                        - Author: Exiled.Updater
                                        - Version: 3.1.2.0
                                        - Required Exiled Version: 7.0.0.0
                                        - Prefix: exiled_updater
                                        - Priority: Medium
                                 ShowReportsInGame:
                                        - Author: Denty
                                        - Version: 2.2.2
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: ShowReportsInGame
                                        - Priority: Medium
                                 RemoteKeycard:
                                        - Author: Beryl (Maintained by Parkeymon)
                                        - Version: 3.1.5
                                        - Required Exiled Version: 6.0.0.18
                                        - Prefix: remotekeycard
                                        - Priority: Medium
                                 Exiled.Permissions:
                                        - Author: Exiled Team
                                        - Version: 7.0.0.0
                                        - Required Exiled Version: 7.0.0.0
                                        - Prefix: exiled_permissions
                                        - Priority: Medium
                                 DiscordIntegration:
                                        - Disabled
                                        - Author: DiscordIntegration
                                        - Version: 7.0.0.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: discord_integration
                                        - Priority: Medium
                                 CustomItems:
                                        - Disabled
                                        - Author: Exiled Team
                                        - Version: 7.0.1.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: custom_items
                                        - Priority: Medium
```

**Additional context**
This almost always results in large lobbies being stuck in a loop of timing out and reconnecting

**Comment by VALERA771** [comment] 2023-05-27 16:48
Is it happening only if 079 was spawned by game in the round start or when player's role was forced through RA too?

**Comment by not-pyroman** [comment] 2023-05-27 19:55
it happens if 079 spawns through _any_ means, including RA.

**Comment by Misaka-ZeroTwo** [comment] 2023-05-28 14:43
Hmmm, when I tried to reproduce the issue with two players, can’t seem to replicate it.

**Comment by not-pyroman** [comment] 2023-05-29 03:00
What exactly are you doing? I'm not sure why it would be crashing my server consistently given none of those plugins use that scanning event afaik, but not yours

**Comment by VALERA771** [comment] 2023-05-29 09:13
We're testing issues on exiled without plugin.

We reproduce it by spawning SCP-079 on empty server and playing as it some time. As you said bug also happens if force player to -70 through RA

**Comment by Misaka-ZeroTwo** [comment] 2023-05-29 15:57
> What exactly are you doing? I'm not sure why it would be crashing my server consistently given none of those plugins use that scanning event afaik, but not yours

I was testing with Exiled and DevTools only, no plugins messing with it. Only two player objects in game.

Procedure:
1. Start two instances of the game.
2. Both join the server
3. Start the round
4. Forceclass SCP to 079
5. Teleport the Class D to the room that 079 is watching
6. Mess with 079's ability, including scanning
7. nothing happened

**Comment by not-pyroman** [comment] 2023-05-29 20:41
The crash on our end occurs instantly, as in when I was testing to reproduce it the server would crash before the 079 had the chance to do anything at all. I don't think this would influence it much, but the server is running on Linux

**Comment by not-pyroman** [comment] 2023-05-29 21:24
I might see if GDB will give any more insight or if something is corrupt somehow
Also to make sure this is the testing release in the Exiled Beta discord channels you're checking?

**Comment by Misaka-ZeroTwo** [comment] 2023-06-02 11:03
Closing due to changes being reverted.

**Closed by Misaka-ZeroTwo** 2023-06-02 11:03 UTC
Labels: question, regarding-events, requires-testing, regarding-transpiler
