### ISSUE TITLE
[BUG] LungingEventArgs doesn't get called

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [Exiled-Team/EXILED#1734] opened 2023-04-20 07:14 UTC
Reported by @ITeMbI4 in https://discord.com/channels/656673194693885975/1064138679171428373/1064138679171428373

**Comment by ITeMbI4** [comment] 2023-04-20 07:17
Should be fixed in https://github.com/Exiled-Team/EXILED/pull/1709
But need testing

**Comment by joker-119** [comment] 2023-04-20 19:22
The above fix is not a valid "fix" for this bug, as it doesn't fix the event, instead it adds a new, different event, that is fired at a different time with different arguments.

#1790 is therefore not a bugfix, but a new feature.

**Comment by VALERA771** [comment] 2023-04-20 19:38
I couldn't find other methods that call before lunge so this is the only way I could "fix" it

**Closed** 2023-06-15 08:43 UTC
Labels: bug, regarding-events, P2
