### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Miramista091** [Exiled-Team/EXILED#1813] opened 2023-05-20 09:28 UTC
When i start the servor i see this : [WARN] [Exiled.Permissions] Permissions file at C:\Users\blond\AppData\Roaming\EXILED\Configs\permissions.yml is missing, creating.

I dont understand what i need to do.

**Comment by VALERA771** [comment] 2023-05-20 12:50
Not a bug. It means that it's created permission file in EXILED directiory. This is normal

**Comment by VALERA771** [comment] 2023-05-20 14:05
Also if you have another issues before posting them here as a bug ask about them in [support channel](https://discord.com/channels/656673194693885975/656709515936530445)

**Comment by Misaka-ZeroTwo** [comment] 2023-05-20 14:29
> Not a bug. It means that it's created permission file in EXILED directiory. This is normal

Closing, because ^

**Closed** 2023-05-20 14:29 UTC
Labels: invalid
